SDL_AUDIO_DRIVER=pulse gamemoderun gamescope -f -W 2560 -H 1440 -w 1024 -h 768 --expose-wayland --force-grab-cursor -- %command% -fullscreen -console -novid  -nojoy 

# SDL_AUDIO_DRIVER=pulse gamemoderun gamescope -f -W 2560 -H 1440 -w 1024 -h 768 --expose-wayland --force-grab-cursor -- %command% -fullscreen -console -novid  -nojoy

Set:  

sudo setcap 'cap_sys_nice=eip' /usr/bin/gamescope

And in launch options: 

LD_PRELOAD= gamescope -- env LD_PRELOAD="$LD_PRELOAD" %command%

LD_PRELOAD="" SDL_AUDIO_DRIVER=pulse gamemoderun gamescope -f -W 2560 -H 1440 -w 1024 -h 768 --expose-wayland --force-grab-cursor -- env LD_PRELOAD="$LD_PRELOAD" %command% -fullscreen -console -novid  -nojoy

More info here: 

https://github.com/ValveSoftware/gamescope/issues/697
